config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/authors", to: "authors#index", as: "authors"
  post "/authors", to: "authors#create"
  get "/authors/new", to: "authors#new", as: "new_author"
  get "/authors/:id", to: "authors#show", as: "author"
  patch "/authors/:id", to: "authors#update"
  put "/authors/:id", to: "authors#update"
  get "/authors/:id/edit", to: "authors#edit", as: "edit_author"
  delete "/authors/:id", to: "authors#destroy"

  resources :genres
  resources :books

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_one :address, dependent: :destroy
    # dependent will allow us to destroy an author and the address associated with that author
    # long way of doing this when rails convention is not completely followed
    # has_one :address, class_name: "Address", foreign_key: "author_id"

    has_many :books, dependent: :destroy
    has_many :images, as: :imageable
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :books_genres
  has_many :genres, through: :books_genres
  has_many :images, as: :imageable
end

app/models/books_genre.rb
class BooksGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books_genres
    has_many :books, through: :books_genres
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    def index 
        @authors = Author.all
    end

    def create 
        Author.create(name: params["name"], date_of_birth: params["date_of_birth"])
        p params

        redirect_to authors_path
    end

    def new 
    end

    def show 
    end

    def edit
        # @author_id = params[:id].to_i
        # @author = Author.update(@author_id])
    end

    def update 
        # @bookmark_id = params[:id].to_i
        # session[:bookmarks][@bookmark_id] = params[:bookmark]

        redirect_to authors_path
    end

    def destroy
        # @bookmark_id = params[:id].to_i
        # session[:bookmarks].delete_at(@bookmark_id)
        
        redirect_to authors_path
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end

    def show
    
    end
    
    def new
        
    end

    def create
    
    end

    def edit
    
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index 
        @genres = Genre.all 
    end

    def new 

    end

    def create 
        p params
        Genre.create(name: params[:genre]["name"])
        redirect_to genres_path
    end
    
    def show 
        @genre = Genre.find(params[:id])
        @books = Genre.find(params[:id]).books
    end   
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Date of Birth</td>
        </tr>
    <thead>
    <tbody>
    <% @authors.each_with_index do |author, index| %>
        <tr>
            <td><%= author["name"] %></td>
            <td><%= author["date_of_birth"] %></td>
            <td><%= link_to('Show', author_path(index)) %></td>
            <td><%= link_to('Edit', edit_author_path(index)) %></td>
            <td><%= link_to('Destroy', author_path(index), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
        </tr> 
    <% end %>
    <tbody>
</table>

<div>
    <%= link_to("Add New Author", new_author_path) %>
</div>

app/views/authors/new.html.erb
<h1>Add New Author</h1>

<form action="<%= authors_path %>" method="POST">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <label for="name">Name</label>
    <input type="text" name="author[name]" id="name" placeholder="Enter Name" />
    
    <label for="dob">Date of Birth</label>
    <input type="date" name="author[date_of_birth]" id="dob" placeholder="Enter Date of Birth" />

    <input type="submit" value="Add Author" />
</form>

app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_for @book, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
f
<% end %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<ul>
    <% @genres.each do |genre| %>
            <li><%= link_to(genre.name, genre_path(genre.id)) %></li>
    <% end %>
</ul>

<div>
    <%= link_to("Add New Genre", new_genre_path) %>
</div>

app/views/genres/new.html.erb
<h1>Add New Genre</h1>

<form action="<%= genres_path %>" method="POST">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

    <label for="name">Name</label>
    <input type="text" name="genre[name]" id="name" placeholder="Enter Genre" />

    <input type="submit" value="Add Genre" />
</form>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<ul>
    <% @books.each do |book| %>
            <li><%= book.title %> , <%= book.author.name %></li>
    <% end %>
</ul>

<div>
    <%= link_to("Back to Genres", genres_path) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationsLesson</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>